-- MySQL Script generated by MySQL Workbench
-- Wed Aug 17 00:49:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SistemaBancosDSTP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SistemaBancosDSTP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaBancosDSTP` DEFAULT CHARACTER SET utf8 ;
USE `SistemaBancosDSTP` ;

-- -----------------------------------------------------
-- Table `SistemaBancosDSTP`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaBancosDSTP`.`USUARIOS` (
  `ID_USUARIO` VARCHAR(50) NOT NULL,
  `NOMBRE` VARCHAR(50) NULL,
  PRIMARY KEY (`ID_USUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaBancosDSTP`.`CLIENTE_BANCO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaBancosDSTP`.`CLIENTE_BANCO` (
  `ID` VARCHAR(50) NOT NULL,
  `USUARIO_ID` VARCHAR(50) NULL,
  `BANCO_ID` VARCHAR(50) NULL,
  `CUENTA_ID` VARCHAR(50) NULL,
  `CREDITO_ID` VARCHAR(50) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaBancosDSTP`.`CUENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaBancosDSTP`.`CUENTA` (
  `ID_CUENTA` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_CUENTA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaBancosDSTP`.`CUENTAS_BASICAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaBancosDSTP`.`CUENTAS_BASICAS` (
  `ID_CUENTA` VARCHAR(50) NOT NULL,
  `SALDO` FLOAT NULL,
  PRIMARY KEY (`ID_CUENTA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaBancosDSTP`.`CUENTAS_VIRTUALES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaBancosDSTP`.`CUENTAS_VIRTUALES` (
  `ID_CUENTA_VIRTUAL` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_CUENTA_VIRTUAL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaBancosDSTP`.`CREDITOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaBancosDSTP`.`CREDITOS` (
  `ID_CREDITO` VARCHAR(50) NOT NULL,
  `MONTO` FLOAT NULL,
  PRIMARY KEY (`ID_CREDITO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaBancosDSTP`.`BANCOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaBancosDSTP`.`BANCOS` (
  `ID_BANCO` VARCHAR(50) NOT NULL,
  `DEPOSTIO` FLOAT NULL,
  PRIMARY KEY (`ID_BANCO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaBancosDSTP`.`BITCOINS_CUENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaBancosDSTP`.`BITCOINS_CUENTA` (
  `ID_BITCOIN_CUENTA` VARCHAR(50) NOT NULL,
  `CUENTA_ID` VARCHAR(50) NULL,
  `ID_BITCOIN` VARCHAR(45) NULL,
  `CANTIDAD` FLOAT NULL,
  PRIMARY KEY (`ID_BITCOIN_CUENTA`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
